Add ISO3-codes to the native regions of the REMIND model (#32)
iiasa/eu-climate-advisory-board-workflow pull request #39
Opened 2023-02-09 15:45 UTC by danielhuppmann

For use in automated processing and validation, this PR adds the ISO3-codes to the native regions of the REMIND model - could you please double-check and add the right ISO3-codes for the European regions?

2023-02-09 16:44 UTC, Renato-Rodrigues requested changes
I added some corrections in one of the files. 
They should be carried to the others.

2023-02-09 16:44 UTC, Renato-Rodrigues commented on definitions/region/model_native_regions/REMIND_2.0.yml
> +      countries: ''
```suggestion
      countries: 'CZE, EST, LVA, LTU, POL, SVK'
```

2023-02-09 16:44 UTC, Renato-Rodrigues commented on definitions/region/model_native_regions/REMIND_2.0.yml
> +      countries: ''
```suggestion
      countries: 'BGR, HRV, HUN, ROU, SVN'
```

2023-02-09 16:44 UTC, Renato-Rodrigues commented on definitions/region/model_native_regions/REMIND_2.0.yml
> +      countries: ''
```suggestion
      countries: 'ALA, DNK, FRO, FIN, SWE'
```

2023-02-09 16:44 UTC, Renato-Rodrigues commented on definitions/region/model_native_regions/REMIND_2.0.yml
> +      countries: ''
```suggestion
      countries: 'CYP, GRC, ITA, MLT'
```

2023-02-09 16:44 UTC, Renato-Rodrigues commented on definitions/region/model_native_regions/REMIND_2.0.yml
> +      countries: ''
```suggestion
      countries: 'PRT, ESP'
```

2023-02-09 16:44 UTC, Renato-Rodrigues commented on definitions/region/model_native_regions/REMIND_2.0.yml
> +      countries: ''
```suggestion
      countries: 'AUT, BEL, LUX, NLD'
```

2023-02-09 16:44 UTC, Renato-Rodrigues commented on definitions/region/model_native_regions/REMIND_2.0.yml
> +      countries: ''
```suggestion
      countries: 'ISL, LIE, NOR, SJM, CHE, GRL'
```

2023-02-09 16:44 UTC, Renato-Rodrigues commented on definitions/region/model_native_regions/REMIND_2.0.yml
> +      countries: ''
```suggestion
      countries: 'ALB, AND, BIH, VAT, MKD, MCO, MNE, SMR, SRB, TUR'
```

2023-02-09 16:44 UTC, Renato-Rodrigues commented on definitions/region/model_native_regions/REMIND_2.0.yml
> +      countries: ''
```suggestion
      countries: 'ALA, AUT, BEL, BGR, HRV, CYP, CZE, DNK, EST, FRO, FIN, FRA, DEU, GRC, HUN, ITA, LVA, LTU, LUX, MLT, NLD, POL, PRT, ROU, SVK, SVN, ESP, SWE'
```

2023-02-09 16:44 UTC, Renato-Rodrigues commented on definitions/region/model_native_regions/REMIND_2.0.yml
> +      countries: GBR
```suggestion
      countries: GBR, IRL
```

2023-02-09 16:44 UTC, Renato-Rodrigues commented on definitions/region/model_native_regions/REMIND_2.0.yml
> +        SVK, SVN, SWE
```suggestion
        SVK, SVN, SWE, FRA, DEU, ITA, GIB, GGY, GBR
```

2023-02-09 16:44 UTC, Renato-Rodrigues commented on definitions/region/model_native_regions/REMIND_2.0.yml
> +        SLV, SUR, TCD, TTO, URY, VCT, VEN, VGB, VIR
```suggestion
        SLV, SUR, TTO, URY, VCT, VEN, VGB, VIR, BES, CUW, SXM, TCA
```

2023-02-09 16:44 UTC, Renato-Rodrigues commented on definitions/region/model_native_regions/REMIND_2.0.yml
> +        OMN, PSE, QAT, SAU, SDN, TCA, TUN, YEM
```suggestion
        OMN, PSE, QAT, SAU, SDN, TUN, YEM, SYR
```

2023-02-09 16:44 UTC, Renato-Rodrigues commented on definitions/region/model_native_regions/REMIND_2.0.yml
> +        NPL, NRU, PAK, PCN, PHL, PLW, PNG, PRK, PYF, SGP, SLB, TJK, TKL, TLS, TON,
```suggestion
        NPL, NRU, PAK, PCN, PHL, PLW, PNG, PRK, PYF, SGP, SLB, TKL, TLS, TON, THA
```

2023-02-09 16:44 UTC, Renato-Rodrigues commented on definitions/region/model_native_regions/REMIND_2.0.yml
> +      countries: ARM, AZE, BLR, GEO, KAZ, KGZ, MDA, RUS, TKM, UKR, UZB
```suggestion
      countries: ARM, AZE, BLR, GEO, KAZ, KGZ, MDA, RUS, TKM, UKR, UZB, TJK
```

2023-02-09 16:44 UTC, Renato-Rodrigues commented on definitions/region/model_native_regions/REMIND_2.0.yml
> +        SYC, SYR, TGO, THA, TZA, UGA, ZAF, ZMB, ZWE
```suggestion
        SYC, TGO, TZA, UGA, ZAF, ZMB, ZWE, TCD
```

2023-02-10 07:17 UTC, danielhuppmann commented
Thank you @Renato-Rodrigues, I applied your changes to the other models.

2023-02-10 09:37 UTC, merged